// C++ for the Windows Runtime v1.29
// Copyright (c) 2016 Microsoft Corporation

#pragma once


WINRT_EXPORT namespace winrt {

namespace ABI::Windows::Devices::Bluetooth::Background {

struct IBluetoothLEAdvertisementPublisherTriggerDetails;
struct IBluetoothLEAdvertisementWatcherTriggerDetails;
struct IGattCharacteristicNotificationTriggerDetails;
struct IRfcommConnectionTriggerDetails;
struct IRfcommInboundConnectionInformation;
struct IRfcommOutboundConnectionInformation;
struct BluetoothLEAdvertisementPublisherTriggerDetails;
struct BluetoothLEAdvertisementWatcherTriggerDetails;
struct GattCharacteristicNotificationTriggerDetails;
struct RfcommConnectionTriggerDetails;
struct RfcommInboundConnectionInformation;
struct RfcommOutboundConnectionInformation;

}

namespace Windows::Devices::Bluetooth::Background {

struct IBluetoothLEAdvertisementPublisherTriggerDetails;
struct IBluetoothLEAdvertisementWatcherTriggerDetails;
struct IGattCharacteristicNotificationTriggerDetails;
struct IRfcommConnectionTriggerDetails;
struct IRfcommInboundConnectionInformation;
struct IRfcommOutboundConnectionInformation;
struct BluetoothLEAdvertisementPublisherTriggerDetails;
struct BluetoothLEAdvertisementWatcherTriggerDetails;
struct GattCharacteristicNotificationTriggerDetails;
struct RfcommConnectionTriggerDetails;
struct RfcommInboundConnectionInformation;
struct RfcommOutboundConnectionInformation;

}

}
